// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.11.2
// source: status_code.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	// 基础错误码，系统错误
	StatusCode_STATUS_CODE_OK            StatusCode = 0
	StatusCode_STATUS_CODE_UNKNOWN_ERROR StatusCode = 1
	// 中间件错误
	StatusCode_STATUS_CODE_READ_ERROR  StatusCode = 101
	StatusCode_STATUS_CODE_WRITE_ERROR StatusCode = 102
	// 用户操作
	StatusCode_STATUS_CODE_USER_EXIST     StatusCode = 1001
	StatusCode_STATUS_CODE_USER_NOT_EXIST StatusCode = 1002
	StatusCode_STATUS_CODE_ADD_USER_FAIL  StatusCode = 1003
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0:    "STATUS_CODE_OK",
		1:    "STATUS_CODE_UNKNOWN_ERROR",
		101:  "STATUS_CODE_READ_ERROR",
		102:  "STATUS_CODE_WRITE_ERROR",
		1001: "STATUS_CODE_USER_EXIST",
		1002: "STATUS_CODE_USER_NOT_EXIST",
		1003: "STATUS_CODE_ADD_USER_FAIL",
	}
	StatusCode_value = map[string]int32{
		"STATUS_CODE_OK":             0,
		"STATUS_CODE_UNKNOWN_ERROR":  1,
		"STATUS_CODE_READ_ERROR":     101,
		"STATUS_CODE_WRITE_ERROR":    102,
		"STATUS_CODE_USER_EXIST":     1001,
		"STATUS_CODE_USER_NOT_EXIST": 1002,
		"STATUS_CODE_ADD_USER_FAIL":  1003,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_status_code_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_status_code_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_status_code_proto_rawDescGZIP(), []int{0}
}

var File_status_code_proto protoreflect.FileDescriptor

var file_status_code_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x2a, 0xd6, 0x01, 0x0a, 0x0a, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x4f,
	0x4b, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f,
	0x44, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52,
	0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44,
	0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x65, 0x12, 0x1b,
	0x0a, 0x17, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x57, 0x52,
	0x49, 0x54, 0x45, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x66, 0x12, 0x1b, 0x0a, 0x16, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f,
	0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0xe9, 0x07, 0x12, 0x1f, 0x0a, 0x1a, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54,
	0x5f, 0x45, 0x58, 0x49, 0x53, 0x54, 0x10, 0xea, 0x07, 0x12, 0x1e, 0x0a, 0x19, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x44, 0x45, 0x5f, 0x41, 0x44, 0x44, 0x5f, 0x55, 0x53, 0x45,
	0x52, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x10, 0xeb, 0x07, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f,
	0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_status_code_proto_rawDescOnce sync.Once
	file_status_code_proto_rawDescData = file_status_code_proto_rawDesc
)

func file_status_code_proto_rawDescGZIP() []byte {
	file_status_code_proto_rawDescOnce.Do(func() {
		file_status_code_proto_rawDescData = protoimpl.X.CompressGZIP(file_status_code_proto_rawDescData)
	})
	return file_status_code_proto_rawDescData
}

var file_status_code_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_status_code_proto_goTypes = []interface{}{
	(StatusCode)(0), // 0: status_code.StatusCode
}
var file_status_code_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_status_code_proto_init() }
func file_status_code_proto_init() {
	if File_status_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_status_code_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_status_code_proto_goTypes,
		DependencyIndexes: file_status_code_proto_depIdxs,
		EnumInfos:         file_status_code_proto_enumTypes,
	}.Build()
	File_status_code_proto = out.File
	file_status_code_proto_rawDesc = nil
	file_status_code_proto_goTypes = nil
	file_status_code_proto_depIdxs = nil
}
