// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.11.2
// source: address.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Province int32

const (
	Province_PROVINCE_UNKNOWN   Province = 0 // 枚举值首位必须是0。主要是为了兼容proto2。实际使用pb时，变量名为Type_VARNAME，也就是Province_PROVINCE_UNKNOWN
	Province_PROVINCE_BEIJING   Province = 1
	Province_PROVINCE_SHANGHAI  Province = 2
	Province_PROVINCE_GUANGDONG Province = 3
)

// Enum value maps for Province.
var (
	Province_name = map[int32]string{
		0: "PROVINCE_UNKNOWN",
		1: "PROVINCE_BEIJING",
		2: "PROVINCE_SHANGHAI",
		3: "PROVINCE_GUANGDONG",
	}
	Province_value = map[string]int32{
		"PROVINCE_UNKNOWN":   0,
		"PROVINCE_BEIJING":   1,
		"PROVINCE_SHANGHAI":  2,
		"PROVINCE_GUANGDONG": 3,
	}
)

func (x Province) Enum() *Province {
	p := new(Province)
	*p = x
	return p
}

func (x Province) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Province) Descriptor() protoreflect.EnumDescriptor {
	return file_address_proto_enumTypes[0].Descriptor()
}

func (Province) Type() protoreflect.EnumType {
	return &file_address_proto_enumTypes[0]
}

func (x Province) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Province.Descriptor instead.
func (Province) EnumDescriptor() ([]byte, []int) {
	return file_address_proto_rawDescGZIP(), []int{0}
}

type City int32

const (
	City_CITY_UNKNOWN   City = 0 // 如果Province和City中都出现UNKNOWN，而不是TYPE_UNKNOWN，就会报错`already defined`，所以enum定义的变量是全局唯一的
	City_CITY_CAPITAL   City = 1
	City_CITY_BEIJING   City = 1
	City_CITY_SHANGHAI  City = 2
	City_CITY_GUANGZHOU City = 3
)

// Enum value maps for City.
var (
	City_name = map[int32]string{
		0: "CITY_UNKNOWN",
		1: "CITY_CAPITAL",
		// Duplicate value: 1: "CITY_BEIJING",
		2: "CITY_SHANGHAI",
		3: "CITY_GUANGZHOU",
	}
	City_value = map[string]int32{
		"CITY_UNKNOWN":   0,
		"CITY_CAPITAL":   1,
		"CITY_BEIJING":   1,
		"CITY_SHANGHAI":  2,
		"CITY_GUANGZHOU": 3,
	}
)

func (x City) Enum() *City {
	p := new(City)
	*p = x
	return p
}

func (x City) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (City) Descriptor() protoreflect.EnumDescriptor {
	return file_address_proto_enumTypes[1].Descriptor()
}

func (City) Type() protoreflect.EnumType {
	return &file_address_proto_enumTypes[1]
}

func (x City) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use City.Descriptor instead.
func (City) EnumDescriptor() ([]byte, []int) {
	return file_address_proto_rawDescGZIP(), []int{1}
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Province Province `protobuf:"varint,2,opt,name=province,proto3,enum=address.Province" json:"province,omitempty"`
	City     City     `protobuf:"varint,3,opt,name=city,proto3,enum=address.City" json:"city,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_address_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_address_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_address_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Address) GetProvince() Province {
	if x != nil {
		return x.Province
	}
	return Province_PROVINCE_UNKNOWN
}

func (x *Address) GetCity() City {
	if x != nil {
		return x.City
	}
	return City_CITY_UNKNOWN
}

var File_address_proto protoreflect.FileDescriptor

var file_address_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x75, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2d, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x11, 0x2e, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e,
	0x63, 0x65, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x21, 0x0a, 0x04,
	0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x2e, 0x43, 0x69, 0x74, 0x79, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x2a,
	0x65, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x6e, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x50,
	0x52, 0x4f, 0x56, 0x49, 0x4e, 0x43, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10,
	0x00, 0x12, 0x14, 0x0a, 0x10, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x4e, 0x43, 0x45, 0x5f, 0x42, 0x45,
	0x49, 0x4a, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x50, 0x52, 0x4f, 0x56, 0x49,
	0x4e, 0x43, 0x45, 0x5f, 0x53, 0x48, 0x41, 0x4e, 0x47, 0x48, 0x41, 0x49, 0x10, 0x02, 0x12, 0x16,
	0x0a, 0x12, 0x50, 0x52, 0x4f, 0x56, 0x49, 0x4e, 0x43, 0x45, 0x5f, 0x47, 0x55, 0x41, 0x4e, 0x47,
	0x44, 0x4f, 0x4e, 0x47, 0x10, 0x03, 0x2a, 0x67, 0x0a, 0x04, 0x43, 0x69, 0x74, 0x79, 0x12, 0x10,
	0x0a, 0x0c, 0x43, 0x49, 0x54, 0x59, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00,
	0x12, 0x10, 0x0a, 0x0c, 0x43, 0x49, 0x54, 0x59, 0x5f, 0x43, 0x41, 0x50, 0x49, 0x54, 0x41, 0x4c,
	0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x49, 0x54, 0x59, 0x5f, 0x42, 0x45, 0x49, 0x4a, 0x49,
	0x4e, 0x47, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x43, 0x49, 0x54, 0x59, 0x5f, 0x53, 0x48, 0x41,
	0x4e, 0x47, 0x48, 0x41, 0x49, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x49, 0x54, 0x59, 0x5f,
	0x47, 0x55, 0x41, 0x4e, 0x47, 0x5a, 0x48, 0x4f, 0x55, 0x10, 0x03, 0x1a, 0x02, 0x10, 0x01, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_address_proto_rawDescOnce sync.Once
	file_address_proto_rawDescData = file_address_proto_rawDesc
)

func file_address_proto_rawDescGZIP() []byte {
	file_address_proto_rawDescOnce.Do(func() {
		file_address_proto_rawDescData = protoimpl.X.CompressGZIP(file_address_proto_rawDescData)
	})
	return file_address_proto_rawDescData
}

var file_address_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_address_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_address_proto_goTypes = []interface{}{
	(Province)(0),   // 0: address.Province
	(City)(0),       // 1: address.City
	(*Address)(nil), // 2: address.Address
}
var file_address_proto_depIdxs = []int32{
	0, // 0: address.Address.province:type_name -> address.Province
	1, // 1: address.Address.city:type_name -> address.City
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_address_proto_init() }
func file_address_proto_init() {
	if File_address_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_address_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_address_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_address_proto_goTypes,
		DependencyIndexes: file_address_proto_depIdxs,
		EnumInfos:         file_address_proto_enumTypes,
		MessageInfos:      file_address_proto_msgTypes,
	}.Build()
	File_address_proto = out.File
	file_address_proto_rawDesc = nil
	file_address_proto_goTypes = nil
	file_address_proto_depIdxs = nil
}
